version: '2'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/htpasswd:/etc/htpasswd
    depends_on:
      - nextcloud
      - registry
    networks:
      - nextcloud_network
      - registry_network
      - plex_network

  certbot:
    build: ./certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/digitalocean.ini:/etc/digitalocean.ini

  postgres:
    image: postgres:10.5
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/logs/postgresql
      - ./postgresql/postgresql.conf:/etc/postgresql.conf
    networks:
      - postgres_network

  nextcloud:
    image: nextcloud:15
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres:5432
    volumes:
      - nextcloud_data:/var/www/html/data
      - nextcloud_config:/var/www/html/config
      - nextcloud_apps:/var/www/html/custom_apps
    networks:
      - nextcloud_network
      - postgres_network
    depends_on:
      - postgres

  registry:
    image: registry:2
    networks:
      - registry_network
    volumes:
      - registry_data:/var/lib/registry

  plex:
    image: plexinc/pms-docker
    volumes:
      - plex_data:/config
      - /mnt/media:/data:rshared
    networks:
      - plex_network
    environment:
      - TZ=America/Toronto
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=http://plex.adtac.in:443/
    hostname: plex-adtac-1

networks:
  postgres_network:
  nextcloud_network:
  registry_network:
  plex_network:

volumes:
  postgres_data:
  postgres_logs:
  nextcloud_data:
  nextcloud_config:
  nextcloud_apps:
  registry_data:
  plex_data:
