version: '3'

services:
  nginx_enp2s0:
    build:
      context: ./nginx
      args:
        iface: enp2s0
    ports:
      - 148.251.77.168:80:80
      - 148.251.77.168:443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ${HOME}/www:/www
    depends_on:
      - plex
      - cgit
    networks:
      enp2s0_network:
        ipv4_address: 10.101.1.2

  nginx_wg0:
    build:
      context: ./nginx
      args:
        iface: wg0
    ports:
      - 10.8.12.2:80:80
      - 10.8.12.2:443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ${HOME}/www:/www
    depends_on:
      - transmission
    networks:
      wg0_network:
        ipv4_address: 10.101.2.2

  plex:
    image: plexinc/pms-docker
    volumes:
      - plex_data:/config
      - ${HOME}/media:/data:rshared
    environment:
      - TZ=America/Toronto
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=https://plex.adtac.in/
    hostname: 2.adtac.in
    networks:
      enp2s0_network:
        ipv4_address: 10.101.1.4

  cgit:
    build: ./cgit
    volumes:
      - /home/git:/repos:ro
    networks:
      enp2s0_network:
        ipv4_address: 10.101.1.5

  transmission:
    build: ./transmission
    ports:
      - 51413:51413
    volumes:
      - transmission_data:/var/transmission/data
      - transmission_watch:/var/transmission/watch
      - ${HOME}/dl:/var/transmission/dl
    networks:
      wg0_network:
        ipv4_address: 10.101.2.3
      enp2s0_network:
        ipv4_address: 10.101.1.8

  wpodns:
    image: registry.gitlab.com/adtac/wpodns:latest
    ports:
      - 148.251.77.168:53:5353/udp

networks:
  enp2s0_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: 148.251.77.168
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      driver: default
      config:
        - subnet: 10.101.1.0/24
  wg0_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: 10.8.12.2
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      driver: default
      config:
        - subnet: 10.101.2.0/24

volumes:
  plex_data:
  transmission_data:
  transmission_watch:
