version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/htaccess:/etc/htaccess
      - ${HOME}/www:/www
      - ${HOME}/media/music:/media/music
    networks:
      - plex_network
      - cgit_network
      - transmission_network
      - version_network
      - status_network

  certbot:
    build: ./certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ${HOME}/.config/google-cloud/google-cloud.json:/etc/google-cloud.json

  plex:
    image: plexinc/pms-docker
    volumes:
      - plex_data:/config
      - ${HOME}/media:/data:rshared
    networks:
      - plex_network
    environment:
      - TZ=America/Toronto
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=https://plex.adtac.in/
    hostname: plex-adtac-2

  cgit:
    build: ./cgit
    volumes:
      - /home/git:/repos:ro
    networks:
      - cgit_network

  transmission:
    build: ./transmission
    ports:
      - 51413:51413
    environment:
      TRANSMISSION_PASSWORD: ${TRANSMISSION_PASSWORD}
    volumes:
      - transmission_data:/var/transmission/data
      - transmission_watch:/var/transmission/watch
      - ${HOME}/dl:/var/transmission/dl
    networks:
      - transmission_network

  version:
    image: registry.gitlab.com/commento/misc/version:latest
    networks:
      - version_network

  status:
    image: registry.gitlab.com/commento/misc/status:latest
    environment:
      SQLITE3: /data/status.sqlite3
    networks:
      - status_network
    volumes:
      - status_data:/data

  wpodns:
    image: registry.gitlab.com/adtac/wpodns:latest
    ports:
      - 2.adtac.in:53:53/udp
    networks:
      - wpodns_network

networks:
  plex_network:
  cgit_network:
  transmission_network:
  version_network:
  status_network:
  wpodns_network:

volumes:
  plex_data:
  transmission_data:
  transmission_watch:
  status_data:
