#!/bin/sh

while true; do
  [[ -d /etc/letsencrypt/live/adtac.in ]] && sleep 86400
  certbot certonly \
    --server https://acme-v02.api.letsencrypt.org/directory \
    --preferred-challenges dns \
    -d '*.adtac.in' -d 'adtac.in' \
    --dns-google --dns-google-credentials /etc/google-cloud.json \
    -n --agree-tos --email adtac@adtac.in
  sleep 60
done
