version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - plex_network

  certbot:
    build: ./certbot
    volumes:
      - ${HOME}/.config/letsencrypt:/etc/letsencrypt
      - ${HOME}/.config/digitalocean/digitalocean.ini:/etc/digitalocean.ini

  plex:
    image: plexinc/pms-docker
    volumes:
      - plex_data:/config
      - ${HOME}/media:/data:rshared
    networks:
      - plex_network
    environment:
      - TZ=America/Toronto
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=http://plex.adtac.in:443/
    hostname: plex-adtac-2

  cgit:
    image: ./cgit
    volumes:
      - /home/git:/repos:ro
    networks:
      - cgit_network

networks:
  plex_network:

volumes:
  plex_data:
