version: '2'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ${HOME}/www:/www
      - /var/log/nginx.log:/custom.log
    networks:
      - io_network

  certbot:
    build: ./certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ${HOME}/.config/google-cloud/google-cloud.json:/etc/google-cloud.json

  commento:
    image: registry.gitlab.com/commento/commento-io:latest
    environment:
      COMMENTO_ORIGIN: https://commento.io
      COMMENTO_CDN_PREFIX: https://cdn.commento.io
      COMMENTO_CONFIG_FILE: /etc/commento.env
    volumes:
      - /etc/commento.env:/etc/commento.env
    networks:
      - io_network

networks:
  io_network:
